import {
  Center,
  Flex,
  Heading,
  Avatar,
  Box,
  Text,
  Stack,
  Button,
  Link,
  useColorModeValue,
  Badge,
  Card,
  CardBody,
} from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";

const skills = [
  "React",
  "Redux",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "GITHUB",
];

const experience = [
  {
    position: "Full Stack WEb Developer",
    organization: "Masai",
    from_to: "July 2022 - Present",
  },
  {
    position: "Quality Assurance Engineer",
    organization: "Peramount Forge and Fitting",
    from: "Oct 2020 - Nov 2021",
  },
];

let data = {
  login: "AshokPrjapati",
  id: 107603976,
  node_id: "U_kgDOBmnoCA",
  avatar_url: "https://avatars.githubusercontent.com/u/107603976?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AshokPrjapati",
  html_url: "https://github.com/AshokPrjapati",
  followers_url: "https://api.github.com/users/AshokPrjapati/followers",
  following_url:
    "https://api.github.com/users/AshokPrjapati/following{/other_user}",
  gists_url: "https://api.github.com/users/AshokPrjapati/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/AshokPrjapati/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AshokPrjapati/subscriptions",
  organizations_url: "https://api.github.com/users/AshokPrjapati/orgs",
  repos_url: "https://api.github.com/users/AshokPrjapati/repos",
  events_url: "https://api.github.com/users/AshokPrjapati/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/AshokPrjapati/received_events",
  type: "User",
  site_admin: false,
  name: "Ashok Kumar",
  company: "Masai School",
  blog: "ashokprjapati.github.io",
  location: "Pali Rajasthan",
  email: null,
  hireable: null,
  bio: "Solution-driven Full Stack Web Developer skilled in MERN Stack. Highly passionate about building web applications and problem-solving.",
  twitter_username: null,
  public_repos: 13,
  public_gists: 0,
  followers: 62,
  following: 48,
  created_at: "2022-06-16T05:17:24Z",
  updated_at: "2022-12-28T12:58:50Z",
};

export default function Home({ data }) {
  const bg = useColorModeValue("gray.50", "gray.800");
  console.log(data);
  let { avatar_url, login, name } = data;
  return (
    <>
      <Head>
        <title>{name} Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Box>
          <Center py={6}>
            <Box
              maxW={"320px"}
              w={"full"}
              bg={useColorModeValue("white", "gray.900")}
              boxShadow={"lg"}
              rounded={"lg"}
              p={6}
              textAlign={"center"}
            >
              <Avatar
                size={"xl"}
                src={avatar_url}
                alt={"Avatar Alt"}
                mb={4}
                pos={"relative"}
                _after={{
                  content: '""',
                  w: 4,
                  h: 4,
                  bg: "green.300",
                  border: "2px solid white",
                  rounded: "full",
                  pos: "absolute",
                  bottom: 0,
                  right: 3,
                }}
              />
              <Heading fontSize={"2xl"} fontFamily={"body"}>
                {name}
              </Heading>
              <Text fontWeight={600} color={"gray.500"} mb={4}>
                @{login}
              </Text>
              <Text
                textAlign={"center"}
                color={useColorModeValue("gray.700", "gray.400")}
                px={3}
              >
                {" "}
                HTML | CSS | JAVASCRIPT | TYPESCRIPT | REACT | REDUX | GITHUB
              </Text>

              <Stack mt={8} direction={"row"} spacing={4}>
                <Link to="https://drive.google.com/file/d/1P27IWs5s4X1JBKLqUAMapYS6an5D_wvH/view?usp=share_link">
                  <Button
                    flex={1}
                    fontSize={"sm"}
                    rounded={"full"}
                    _focus={{
                      bg: "gray.200",
                    }}
                  >
                    Resume
                  </Button>
                </Link>

                <Button
                  flex={1}
                  fontSize={"sm"}
                  rounded={"full"}
                  bg={"blue.400"}
                  color={"white"}
                  boxShadow={
                    "0px 1px 25px -5px rgb(66 153 225 / 48%), 0 10px 10px -5px rgb(66 153 225 / 43%)"
                  }
                  _hover={{
                    bg: "blue.500",
                  }}
                  _focus={{
                    bg: "blue.500",
                  }}
                >
                  Follow
                </Button>
              </Stack>
            </Box>
          </Center>

          <Box
            maxW={"320px"}
            w={"full"}
            bg={useColorModeValue("white", "gray.900")}
            boxShadow={"lg"}
            rounded={"lg"}
            p={6}
            textAlign={"center"}
          >
            {skills.map((s, i) => (
              <Badge key={i} px={2} py={1} bg={bg} fontWeight={"400"}>
                {s}
              </Badge>
            ))}
          </Box>

          <Card
            mt={"10px"}
            maxW={"320px"}
            w={"full"}
            bg={useColorModeValue("white", "gray.900")}
            boxShadow={"lg"}
            rounded={"lg"}
            p={6}
            textAlign={"center"}
          >
            {experience.map((e, i) => (
              <CardBody key={i}>
                <Avatar
                  border={i == 0 ? "3px solid blue" : "none"}
                  name={`${i + 1}`}
                  src=""
                />
                <Box>
                  <Text as="h4">
                    {e.position} at {e.organization}
                  </Text>
                  <Text as="p">{e.from_to}</Text>
                </Box>
              </CardBody>
            ))}
          </Card>
        </Box>
      </Flex>
    </>
  );
}

let username = "AshokPrjapati";

export async function getStaticProps(context) {
  let res = await axios.get(`https://api.github.com/users/${username}`);
  let data = await res.data;
  return {
    props: {
      data: data,
    }, // will be passed to the page component as props
  };
}
